let items=[];
function addCart(name){if(!items.includes(name))items.push(name);renderCart();document.getElementById('cart-panel').classList.add('open');document.getElementById('backdrop').classList.add('show')}
function toggleCart(){document.getElementById('cart-panel').classList.toggle('open');document.getElementById('backdrop').classList.toggle('show')}
function renderCart(){document.getElementById('cart-count').textContent=`(${items.length})`;document.getElementById('bag-number').textContent=`(${items.length})`;let el=document.getElementById('cart-items');el.innerHTML=items.length?items.map((x,i)=>`<div class="cart-item"><span>${x}<br><small>Exclusive licence</small></span><span>KES ${i===1?'8,500':'7,500'}</span></div>`).join(''):'<p class="empty">Your bag is empty.<br>Find your next sound in the vault.</p>'}
document.addEventListener('mousemove',e=>{let c=document.querySelector('.cursor-glow');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});
document.querySelectorAll('.play').forEach(p=>p.addEventListener('click',()=>{p.textContent=p.textContent==='▶'?'❚❚':'▶'}));
document.querySelector('.contact-form')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const name=form.querySelector('input').value.trim();const message=form.querySelector('textarea').value.trim();const service=form.querySelectorAll('input')[1].value.trim();const subject=encodeURIComponent(`KROME website enquiry${service?` — ${service}`:''}`);const body=encodeURIComponent(`Name: ${name}\nService: ${service}\n\n${message}`);window.location.href=`mailto:hello@krome.co.ke?subject=${subject}&body=${body}`;});
document.querySelector('.menu-btn')?.addEventListener('click',()=>{document.querySelector('.nav')?.classList.toggle('mobile-open');});
document.querySelectorAll('.filter').forEach(group=>group.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;group.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');}));
